name = "slayground"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"



[[d1_databases]]
binding = "DB"
database_name = "slayground-db"
database_id = "2197eac-aa17-c4cf-7c4da-3c16f7c0a37b"
